import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"], // optional: customize which weights you need
});

export const metadata: Metadata = {
  title: "Quippos | Finnegans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${poppins.variable} font-sans antialiased bg-linear-to-b from-[#e8d8ff] to-[#04102d]`}
      >
        {children}
      </body>
    </html>
  );
}
